server:
  port: 8084
spring:
  application:
    name: fly-notice-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${fly.eurekaClientServiceUrlDefaultZone}
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}