server:
  port: 8000
spring:
  application:
    name: fly-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fanpan26/spring-cloud-config.git
          #search-paths: fly-*-service
          clone-on-start: true
        health:
          repositories:
            fly-user-service:
              lable: master
              name: fly-user-service
              profiles: default
management:
  endpoint:
    health:
      show-details: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://panzi:123456@eureka1:8761/eureka/,http://panzi:123456@eureka2:8762/eureka/
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    metadata-map:
      description: config center