server:
  port: 8081
spring:
    application:
       name: fly-user-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${fly.eurekaClientServiceUrlDefaultZone}
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
logging:
  level:
    org:
      springframework:
        security: DEBUG
