server:
  port: 8081
eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    metadata-map:
      description: user service,base api,account api
spring:
  rabbitmq:
    host: 192.168.187.129
    port: 5672
    username: panzi
    password: 123456
    virtual-host: fly
logging:
  level:
    org:
      springframework:
        security: INFO
        boot: DEBUG
