server:
  port: 8081
spring:
    application:
       name: fly-user-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://panzi:123456@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
