spring:
  application:
    name: eureka-server
  profiles: eureka1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1
  client:
    service-url:
    # server1 注册到server2上
      defaultZone: http://panzi:123456@eureka2:8762/eureka/
    register-with-eureka: true