server:
  port: 8762
spring:
  application:
    name: eureka-server
  profiles: eureka2
eureka:
  instance:
    hostname: eureka2
  client:
    service-url:
    # server2 注册到server1 上
      defaultZone: http://panzi:123456@eureka1:8761/eureka/
    register-with-eureka: true
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}